### PR TITLE
Possibility to determine the edge touch level

### PR DESCRIPTION
**Pull request by saeedmozaffari**
users can determine edge level touch as : MAX,MED,MIN or directly set width pixel of device

### CODE REVIEW

**Comment by saeedmozaffari** [comment]
proguard need

```
-keepclassmembers class android.support.v4.widget.ViewDragHelper {
    private <fields>;
}
```

**Comment by YoKeyword** [comment]
Coooool
Thanks.

**Review by ayaanali110 — APPROVED** [review]
Skyl.m## @ay@mufta

**Comment by ayaanali110** [comment]
@ayaanali110 []()[]()

**Pull request merged**
